
////////////////////////////////////////
// :offer: = tilfeldig offer          //
// :handling: = tilfeldig handling    //
////////////////////////////////////////

let handlinger = [
    'skriker på',
    'slikker på',
    'tuter på',
    'slår',
    'rister',
    'gir MDMA til',
    'angriper',
    'truer',
    'kidnapper',
    'voldtar',
    'doper ned',
    'tar på',
    'ser på',
    'beføler',
    'spionerer på',
    'stalker',
    'filmer',
    'sniffer kokain med',
    'sniffer kokain fra navelen til',
    'tar dop med',
    'har sex med',
    'sniffer',
    'flirter med',
    'kaster egg på',
    'hoster på',
    'kaster maling på',
    'river av håret på',
    'hopper på taket til',
    'banker på vinduet til',
    'kaster egg på huset til',
    'kaster egg på vinduet til',
    'heller maling utenfor huset til',
    'smører bløtkake på',
    'klipper gresset til',
    'holder fast',
    'spiller høy musikk ved',
    'kaster isbiter etter',
    'syr dresser til',
    'handler på bunnpris til',
    'jobber på bunnpris med',
    'selger dop til',
    'selger heroin til',
    'drar av trusa til',
    'kler av',
    'tegner på',
    'viser nazi-hilsen til',
    'stjeler sykkelen til',
    'laster ned barneporno til',
    'runker til',
    'runker',
    'onanerer til',
    'penetrerer',
    'angriper',
    'overfaller',
    'flirter med',
    'sniffer kokain med',
    'tar dop med',
    'roofer',
    'sniffer de brukte stringtrusene til',
    'kaster maling på',
    'river av håret til',
    'skriker utenfor vinduet til',
    'smører bløtkake på',
    'klipper gresset til',
    'holder fast',
    'spiller høy musikk for',
    'kaster isbiter etter katten til',
    'syr dresser av',
    'kjøper bunnpris-sko til',
    'jobber på bunnpris og filmer',
    'river av trusa på',
    'smører bløtkake på',
    'beføler',
    'heller melk over',
    'onanerer til',
    'tafser på',
    'ber om å bli straffet av',
    'fingrer',
    'utrydder',
    'voldspenetrerer',
    'holder nabolaget fritt for',
    'laster ned barneporno med',
    'lager pornofilm med',
    'ser på horseporn med',
    'lukter på håret til',
    'begår folkemord av',
    'slutter seg til en terrorgruppe med',
    'dreper',
    'henretter',
    'forurenser drikkevannet til',
    'putter giftige stoffer i drikkevannet til',
    'drar frem kuken sin foran',
    'flasher',
    'tar bilde av',
    'skriker utenfor huset til',
    'står utenfor huset til',
    'gjemmer seg fra politiet i hagen til',
    'tisser på huset til',
    'tisser på døren til',
    'uriner offentlig sammen med',
    'urinerer i sengen til',
    'gjemmer seg under sengen til',
    'gjemmer seg i hagen til',
    'river av klærene sine foran',
    'river av klærene til',
    'bruker kikkert til å se på',
    'sniker seg utenfor huset til',
    'banker på døren til naboen for å informere dem at han er en dømt sexforbryter sammen med',
    'begår bedrageri imot',
    'begår skattesvindel med',
    'raner',
    'blir arrestert av politiet med'
]

let offere = [
    'politiet',
    'uniformerte damer',
    'gamle damer',
    'datteren sin',
    'moren sin',
    'nyfødte barn',
    'barnehagebarn',
    'politisjefen',
    'seg selv',
    'gamle menn',
    'ungdomskole elever',
    'Borgar',
    'Brede',
    'Adrian',
    'Brian',
    'Jonas',
    'faren sin',
    'søskenbarnet sitt',
    'søsteren sin',
    'dyr',
    'sauer',
    'kuer',
    'innvandrere',
    'barnehagetanter',
    'rektor',
    'chrest',
    'jøder',
    'prester',
    'apekatter',
    'helseministeren',
    'kulturministeren',
    'statsministeren',
    'miljøaktivister',
    'paven',
    'barnehagebarn',
    'Christian Tharaldsen',
    'prestene',
    'apekatter',
    '09',
    '08',
    '07',
    '06',
    'kusina si',
    'fettern sin',
    'onkelen sin',
    'tanta si',
    'stesøstera si',
    'samtlige familiemedlemmer',
    'barn',
    'ekkorn',
    'hester',
    'isbjørner',
    'hunder og katter',
    'gullfisker',
    'kaniner',
    'muslimer',
    'kristne damer',
    'kristne',
    'jehovas vitner',
    'terrorister',
    'al-qaeda medlemmer',
    'isis medlemmer',
    'barn med nedsatt funksjonsevne',
    'gamle damer med nedsatt funksjonsevne',
    'tilbakestående folk',
    'unger med kroniske sykdommer',
    'greta thunberg',
    'profeten muhammed',
    'minoritetsgrupper',
    '6 år gamle jenter',
    '6 år gamle barn',
    'medlemmer av regjeringen',
    'mindreårige',
    'veldedighetsorganisasjoner'
]

let tider = [
    'klokka 3 på natta',
    'midt på dagen',
    'før skola',
    'når han er hjemme',
    'når han står utenfor politistansjonen',
    'mens han løper fra barneskola',
    'mens han løper fra barneskole lærere',
    'midt på natta',
    'klokka 5 om morgenen',
    'når han er på ferie',
    'utenfor ungdomsskolen',
    'foran barn',
    'foran gamle damer',
    'foran gamle menn',
    'på fritiden',
    'på Gravberget',
    'i Sørskogbygda',
    'i Rendalen',
    'i Charlottenberg',
    'i gullgruven i Aserbajdsjan',
    'på klistremerkefabrikken',
    'på steinbruddet',
    'på gamlehjemmet',
    'på narvesen på Rena',
    'på brunnpris',
    'på postkontoret',
    'i Ålesund',
    'på kebab sjappa i Karlstad',
    'mens han løper fra politiet',
    'mens han kjører fra politiet',
    'mens han kjøper pultost',
    'mens han har sex',
    'mens han tar heroin',
    'når han er høy på harde stoffer',
    'i fødeavdelingen på sykehuset',
    'hos kda',
    'på rektors kontor',
    'sammen med Martin',
    'når han har sex',
    'når han ser på gay furry midget horseporn',
    'i bolivia',
    'når han har tatt store mengder narkotika',
    'foran :offer:',
    'mens :offer: ser på',
    'når han er på kreftavdelingen på sykehuset',
    'mens han er på barneavdelingen på sykehuset',
    'når han er på sykehusavdelingen med barn som har kroniske sykdommer',
    'mens han ber til allah',
    'mens han leser bibelen',
    'mens han brenner bibelen',
    'mens han brenner koranen',
    'mens han brenner det norske flagget',
    'mens han brenner hellige skrifter',
    'mens han leser hellige skrifter',
    'på kvelden',
    'i helgene',
    'i kirka',
    'i en moske',
    'i mørket',
    'utenfor huset til en pedofil',
    'mens han holder på tissen til :offer:',
    'mens han runker til bilder av :offer:',
    'mens han tenker på :offer:',
    'mens han stryker på låret til :offer:',
    'mens han banker på døren til :offer: for å informere dem om at han er dømt sexforbryter',
    'mens han vitner imot :offer: i en rettsak hvor de :handling:',
    'foran en dommer i rettsaken sin for å bryte § 310, Fremvisning av seksuelle overgrep mot barn eller fremvisning som seksualiserer barn',
    'i 1 - World Trade Center',
    'mens han planlegger et terrorangrep imot den norske staten',
    'mens han begår bedrageri imot :offer:',
    'mens han begår skatte- og avgiftsundrager',
    'mens han gjør handlinger som strider imot § 305, Seksuelt krenkende atferd mv. overfor barn under 16 år',
    'når han deltar i biologiolympiaden i de forente arabiske emirater',
    'mens han er i avhør hos politiet',
    'mens han er i avhør for å ha gjort handlinger som strider imot § 266, hensynsløs atferd',
    'mens han gjør handlinger som strider imot § 266 a, alvorlig personforfølgelser imot :offer:',
    'mens han blir arrestert av politiet',
    '',
    'mens han blir dømt til 10 års fengsel for å bryte § 258, Grov menneskehandel'
]
