
////////////////////////////////////////
// :offer: = tilfeldig offer          //
// :handling: = tilfeldig handling    //
// :kjoenn: = riktig pronomen         //
////////////////////////////////////////

let handlinger = [
    'skriker på',
    'slikker på',
    'tuter på',
    'slår',
    'rister',
    'gir MDMA til',
    'angriper',
    'truer',
    'kidnapper',
    'voldtar',
    'doper ned',
    'tar på',
    'ser på',
    'beføler',
    'spionerer på',
    'stalker',
    'filmer',
    'sniffer kokain med',
    'sniffer kokain fra navelen til',
    'tar dop med',
    'har sex med',
    'sniffer',
    'flirter med',
    'kaster egg på',
    'hoster på',
    'kaster maling på',
    'river av håret på',
    'hopper på taket til',
    'banker på vinduet til',
    'kaster egg på huset til',
    'kaster egg på vinduet til',
    'heller maling utenfor huset til',
    'smører bløtkake på',
    'klipper gresset til',
    'holder fast',
    'spiller høy musikk ved',
    'kaster isbiter etter',
    'syr dresser til',
    'handler på bunnpris til',
    'jobber på bunnpris med',
    'selger dop til',
    'selger heroin til',
    'drar av trusa til',
    'kler av',
    'tegner på',
    'viser nazi-hilsen til',
    'stjeler sykkelen til',
    'laster ned barneporno til',
    'runker til',
    'runker',
    'onanerer til',
    'penetrerer',
    'angriper',
    'overfaller',
    'flirter med',
    'sniffer kokain med',
    'tar dop med',
    'roofer',
    'sniffer de brukte stringtrusene til',
    'kaster maling på',
    'river av håret til',
    'skriker utenfor vinduet til',
    'smører bløtkake på',
    'klipper gresset til',
    'holder fast',
    'spiller høy musikk for',
    'kaster isbiter etter katten til',
    'syr dresser av',
    'kjøper bunnpris-sko til',
    'jobber på bunnpris og filmer',
    'river av trusa på',
    'smører bløtkake på',
    'beføler',
    'heller melk over',
    'onanerer til',
    'tafser på',
    'ber om å bli straffet av',
    'fingrer',
    'utrydder',
    'voldspenetrerer',
    'holder nabolaget fritt for',
    'laster ned barneporno med',
    'lager pornofilm med',
    'ser på horseporn med',
    'lukter på håret til',
    'begår folkemord av',
    'slutter seg til en terrorgruppe med',
    'dreper',
    'henretter',
    'forurenser drikkevannet til',
    'putter giftige stoffer i drikkevannet til',
    'drar frem kuken sin foran',
    'flasher',
    'tar bilde av',
    'skriker utenfor huset til',
    'står utenfor huset til',
    'gjemmer seg fra politiet i hagen til',
    'tisser på huset til',
    'tisser på døren til',
    'uriner offentlig sammen med',
    'urinerer i sengen til',
    'gjemmer seg under sengen til',
    'gjemmer seg i hagen til',
    'river av klærene sine foran',
    'river av klærene til',
    'bruker kikkert til å se på',
    'sniker seg utenfor huset til',
    'banker på døren til naboen for å informere dem at :kjoenn: er en dømt sexforbryter sammen med',
    'begår bedrageri imot',
    'begår skattesvindel med',
    'raner',
    'blir arrestert av politiet med',
    'tenner på',
    'tenner på huset til',
    'tenner på håret til',
    'presser :offer: til å utføre mexuelle handlinger med',
    'kjører i 200km/t med',
]

let offere = [
    'politiet',
    'uniformerte damer',
    'gamle damer',
    'datteren sin',
    'moren sin',
    'nyfødte barn',
    'barnehagebarn',
    'politisjefen',
    'gamle menn',
    'ungdomskoleelever',
    'Borgar',
    'Brede',
    'Adrian',
    'Brian',
    'Jonas',
    'faren sin',
    'søskenbarnet sitt',
    'søsteren sin',
    'dyr',
    'sauer',
    'kuer',
    'innvandrere',
    'barnehagetanter',
    'rektor',
    'chrest',
    'jøder',
    'prester',
    'apekatter',
    'helseministeren',
    'kulturministeren',
    'statsministeren',
    'miljøaktivister',
    'paven',
    'barnehagebarn',
    'Christian Tharaldsen',
    'prestene',
    'apekatter',
    '09',
    '08',
    '07',
    '06',
    'kusina si',
    'fettern sin',
    'onkelen sin',
    'tanta si',
    'stesøstera si',
    'samtlige familiemedlemmer',
    'barn',
    'ekkorn',
    'hester',
    'isbjørner',
    'hunder og katter',
    'gullfisker',
    'kaniner',
    'muslimer',
    'kristne damer',
    'kristne',
    'jehovas vitner',
    'terrorister',
    'al-qaeda-medlemmer',
    'isis-medlemmer',
    'barn med nedsatt funksjonsevne',
    'gamle damer med nedsatt funksjonsevne',
    'tilbakestående folk',
    'unger med kroniske sykdommer',
    'greta thunberg',
    'profeten muhammed',
    'minoritetsgrupper',
    '6 år gamle jenter',
    '6 år gamle barn',
    'medlemmer av regjeringen',
    'mindreårige',
    'veldedighetsorganisasjoner'
]

let tider = [
    'klokka 3 på natta',
    'midt på dagen',
    'før skola',
    'når :kjoenn: er hjemme',
    'når :kjoenn: står utenfor politistansjonen',
    'mens :kjoenn: løper fra barneskola',
    'mens :kjoenn: løper fra barneskole lærere',
    'midt på natta',
    'klokka 5 om morgenen',
    'når :kjoenn: er på ferie',
    'utenfor ungdomsskolen',
    'foran barn',
    'foran gamle damer',
    'foran gamle menn',
    'på fritiden',
    'på Gravberget',
    'i Sørskogbygda',
    'i Rendalen',
    'i Charlottenberg',
    'i gullgruven i Aserbajdsjan',
    'på klistremerkefabrikken',
    'på steinbruddet',
    'på gamlehjemmet',
    'på narvesen på Rena',
    'på brunnpris',
    'på postkontoret',
    'i Ålesund',
    'på kebab sjappa i Karlstad',
    'mens :kjoenn: løper fra politiet',
    'mens :kjoenn: kjører fra politiet',
    'mens :kjoenn: kjøper pultost',
    'mens :kjoenn: har sex',
    'mens :kjoenn: tar heroin',
    'når :kjoenn: er høy på harde stoffer',
    'i fødeavdelingen på sykehuset',
    'hos kda',
    'på rektors kontor',
    'sammen med Martin',
    'når :kjoenn: har sex',
    'når :kjoenn: ser på gay furry midget horseporn',
    'i bolivia',
    'når :kjoenn: har tatt store mengder narkotika',
    'foran :offer:',
    'mens :offer: ser på',
    'når :kjoenn: er på kreftavdelingen på sykehuset',
    'mens :kjoenn: er på barneavdelingen på sykehuset',
    'når :kjoenn: er på sykehusavdelingen med barn som har kroniske sykdommer',
    'mens :kjoenn: ber til allah',
    'mens :kjoenn: leser bibelen',
    'mens :kjoenn: brenner bibelen',
    'mens :kjoenn: brenner koranen',
    'mens :kjoenn: brenner det norske flagget',
    'mens :kjoenn: brenner hellige skrifter',
    'mens :kjoenn: leser hellige skrifter',
    'på kvelden',
    'i helgene',
    'i kirka',
    'i en moske',
    'i mørket',
    'utenfor huset til en pedofil',
    'mens :kjoenn: holder på tissen til :offer:',
    'mens :kjoenn: runker til bilder av :offer:',
    'mens :kjoenn: tenker på :offer:',
    'mens :kjoenn: stryker på låret til :offer:',
    'mens :kjoenn: banker på døren til :offer: for å informere dem om at :kjoenn: er dømt sexforbryter',
    'mens :kjoenn: vitner imot :offer: i retten',
    'foran en dommer i rettsaken sin for å bryte § 310, Fremvisning av seksuelle overgrep mot barn eller fremvisning som seksualiserer barn',
    'i 1 - World Trade Center',
    'mens :kjoenn: planlegger et terrorangrep imot den norske staten',
    'mens :kjoenn: begår bedrageri imot :offer:',
    'mens :kjoenn: begår skatte- og avgiftsundrager',
    'mens :kjoenn: gjør handlinger som strider imot § 305, Seksuelt krenkende atferd mv. overfor barn under 16 år',
    'når :kjoenn: deltar i biologiolympiaden i de forente arabiske emirater',
    'mens :kjoenn: er i avhør hos politiet',
    'mens :kjoenn: er i avhør for å ha gjort handlinger som strider imot § 266, hensynsløs atferd',
    'mens :kjoenn: gjør handlinger som strider imot § 266 a, alvorlig personforfølgelser imot :offer:',
    'mens :kjoenn: blir arrestert av politiet',
    '',
    'mens :kjoenn: blir dømt til 10 års fengsel for å bryte § 258, Grov menneskehandel',
    'mens :kjoenn: tenner på jehovas vitner-bygg',
    'mens :kjoenn: blir varetektfengslet',
    'mens :kjoenn: spionerer på statlige virksomheter for Russland',
    'mens :kjoenn: sprer falsk informasjon på internettet',
    'mens :kjoenn: sprer russisk propaganda om krigen i Ukraina',
    'mens :kjoenn: er på symøte',
    'mens :kjoenn: er på feministmøter',
    

]
